#### Request ####

bool is_xml
# Name of the tree to execute if !isXML else an XML payload for the tree
string tree
# Optional, implementation-dependent, payload.
string payload
---
#### Result ####

# Status of the tree
NodeStatus node_status
# result payload or error message
string return_message
---
#### Feedback ####

#This can be customized by the user
string message
